#.travis.yml

language: node_js
sudo: true
cache:
  directories:
  - node
  - node_modules
dist: trusty
node_js:
- 5.6.0
branches:
  only:
  - master
addons:
apt:
  sources:
  - google-chrome
  packages:
  - google-chrome-stable
  - google-chrome-beta
before_install:
- npm install -g angular-cli
- export CHROME_BIN=/usr/bin/google-chrome
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- ng test --watch false
- ng serve &
- ng e2e
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false