#.travis.yml

language: node_js
node_js:
  - "5.11"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g angular-cli
  - 'export CHROME_BIN=chromium-browser'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - 'npm install -g karma grunt-cli jshint'
  - 'npm install'

script:
  - ng test
  - ng build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change

addons:
  sauce_connect:
    username: Blurri
    access_key: 440bd48c-fada-4bb4-a726-b97d92d3361a